name : first_workflow
on : workflow_dispatch
jobs: 
    first_job:
        runs_on: ubuntu-latest
        steps:
            - name: hello world
              run : echo "hello world"
            - name: bye world
              run : echo "work done bye"